---

- hosts: all
  become: true
  tasks:

- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install package foo from repo
  pacman:
    name: mc
    state: present