---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install mc
    apt:
      name: mc
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install python3
    pacman:
      name: python3
      state: latest
    when: ansible_distribution == "Arch"
  
  - name: install ranger
    apt:
      name: ranger
      state: latest
