---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: remove package >> apache2
    apt:
      name: apache2
      state: absent

  - name: add php
    apt:
      name: remove package >> libapache2-mod-php
      state: absent
