---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debain", "Ubuntu"]

  - name: install mc
    apt:
      name: micro
      state: latest
    when: ansible_distribution in ["Debain", "Ubuntu"]

  - name: install python3
    apt:
      name: python3
      state: latest
