---
- hosts: arch
  #connection: local # When running locally
  #remote_user: toadie
  vars:
    package_names:
      - nano
      - mc
      - duf
      - ranger
      - lsd
      - conky
  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install package if not present Arch
      pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names }}"